services:
  - type: web
    name: expense-tracker-api
    runtime: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
    plan: free